CREATE TABLE LOCACOES
(
ID INT PRIMARY KEY IDENTITY,
CLIENTE INT NOT NULL,
FUNCIONARIO INT NOT NULL,
PRECO FLOAT NOT NULL,
DATALOCACAO DATETIME2 NOT NULL,
DATAPREVISTADEVOLUCAO DATETIME2 NOT NULL,
DATADEVOLUCAO DATETIME2 NULL,
MULTA FLOAT NOT NULL,
CONSTRAINT FK_LOCACOES_CLIENTES FOREIGN KEY (CLIENTE)
REFERENCES CLIENTES,
CONSTRAINT FK_LOCACOES_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO)
REFERENCES FUNCIONARIOS,
)

ALTER TABLE LOCACOES
ADD FOIPAGO BIT NOT NULL

CREATE TABLE LOCACOES_FILMES
(
LOCACAOID INT REFERENCES LOCACOES, 
FILMEID INT REFERENCES FILMES,
PRIMARY KEY (LOCACAOID, FILMEID)
)











